### ISSUE TITLE
Submit form changes in textarea from Sublime

### ISSUE THREAD

**Issue by usrbowe** [Cacodaimon/GhostText-for-SublimeText#48]
I am wondering, is it possible to submit form via Sublime? 

### Use case
If I am having opened code from textarea via GhostText in Sublime, and I edited something.
Now I want to submit these changes to original textarea which is inside <form>.
So I hit some shortcut and these data will be submited via form action.

### Solutions
1) Extracting <form> action url and then send it from Sublime (which should be possible. I saw some httprequest addon for Sublime).
2) Sending action to Chrome from Sublime. And this action will submit this form inside Chrome.
+
Refreshing data from textarea, after submiting form (in case, when you send form and page will redirect back to original with same textarea, but new data inside).

Is this idea possible for impelmenting?

**Comment by Cacodaimon** [comment]
This feature has already been discussed here #44
