### ISSUE TITLE
When activating GT creates multiple tabs in all open ST windows.

### ISSUE THREAD

**Issue by destos** [Cacodaimon/GhostText-for-SublimeText#50]
I've been experiencing this for a while and has hampered my use of GhostText.

Let me know of any steps I can take to get you better debugger output.

**Comment by Cacodaimon** [comment]
Can you please provide more information like OS, browser, page and application versions?

**Comment by destos** [comment]
@Cacodaimon 

OSX 10.10.3 (14D136), Chrome 42.0.2311.135 (64-bit), This comment box, Latest master on both the sublime and chrome package/extension. 

**Some behaviors:**

When activating GT it asks for me to select the text area on the page as there are multiple. I've expereinced this on all the pages I've attempted to use it on github.com. Wiki page editing and in the issues.

Once I click on the text area the multiple tabs are created in sublime.

All the other tabs do not update

![screen shot 2015-04-30 at 10 01 37 pm](https://cloud.githubusercontent.com/assets/136456/7426148/922c1ad6-ef84-11e4-8808-eebf924e896e.png)
.

**Comment by Cacodaimon** [comment]
I can reproduce this behavior with ST Build 3083, I will fix this the next days.

**Comment by destos** [comment]
I have quite a few sublime packages and chrome extensions. I'll try to list them.
**Activated chrome extensions:**
1Password manager
Google Docs
Google Sheets
Google Slides
HTTPS Everywhere
LiveReload
Octotree
React Developer Tools
Reddit Enhancement Suite
Save to Pocket
Spreed
The Great Suspender
uBlock Origin

**For Sublime:**
		"Advanced CSV",
		"AdvancedNewFile",
		"Alignment",
		"All Autocomplete",
		"AngularJS",
		"AngularJS (CoffeeScript)",
		"Arduino-like IDE",
		"AutoFileName",
		"Block Cursor Everywhere",
		"BracketHighlighter",
		"C++11",
		"Case Conversion",
		"Color Highlighter",
		"ColorPicker",
		"CSV",
		"DashDoc",
		"Djaneiro",
		"Django Manage Commands",
		"DjangoNoseTestRunner",
		"DocBlockr",
		"Dockerfile Syntax Highlighting",
		"EditorConfig",
		"Emmet",
		"FileDiffs",
		"FullScreenStatus",
		"G-code Syntax Highlighting",
		"Git",
		"Git Config",
		"GitGutter",
		"GitStatus",
		"Handlebars",
		"HexViewer",
		"HTMLBeautify",
		"Javascript Beautify",
		"Jinja2",
		"JSON Reindent",
		"JSX",
		"LinkOpener",
		"Markdown Extended",
		"Markdown Preview",
		"MarkdownEditing",
		"nginx",
		"Nodejs",
		"Open Search Result",
		"Origami",
		"Package Control",
		"Placehold.it Image Tag Generator",
		"PlainNotes",
		"PostgreSQL Syntax Highlighting",
		"Pretty JSON",
		"Python Improved",
		"Python PEP8 Autoformat",
		"ReactJS",
		"ReadmePlease",
		"requirementstxt",
		"Restructured Text (RST) Snippets",
		"RestructuredText Improved",
		"SaltStack-related syntax highlighting and snippets",
		"Sass",
		"ScopeHunter",
		"SideBarEnhancements",
		"StringEncode",
		"Stylus",
		"sublime-github",
		"SublimeBlockCursor",
		"SublimeGit",
		"SublimeLinter",
		"SublimeLinter-coffeelint",
		"SublimeLinter-cpplint",
		"SublimeLinter-csslint",
		"SublimeLinter-flake8",
		"SublimeLinter-jshint",
		"SublimeLinter-jsxhint",
		"SublimeLinter-pep257",
		"SublimePythonIDE",
		"SublimeREPL",
		"SublimeXiki",
		"TrailingSpaces",
		"URLEncode",
		"Vagrant",
		"Vintage Numbers",
		"Vintage-Origami",
		"VintageLines",
		"Web Inspector",
		"WordCount"

**Comment by Cacodaimon** [comment]
This are a lot of plugins :) .

The first question is, it this a Mac related bug or does any ST or Chrome plugin causes this behavior?

@bfred-it 
Can you reproduce this behavior on your Mac?

@destos 
Can you disable all plugins and check if GT works when all other are disabled?

**Comment by bfred-it** [comment]
What's on the Chrome store and Package Manager is the latest version, right? It works fine for me on this page, regardless of window count and `new_window_on_connect` setting. 

To me it sounds like the Chrome extension is loading twice and opening two separate connections.

* What do you see in Chrome's console?
* Can you enable GT in incognito mode and try it in there?
