### ISSUE TITLE
All I get is a red box with Connection Error

### ISSUE THREAD

**Issue by dtg581** [Cacodaimon/GhostText-for-SublimeText#54]
I tried using Sublime Text and GhostText for Chrome with the html editor in WordPress and the textarea box here on Github where I am typing this text. All that happens when I click the GhostText icon (or Ctrl-Shift-K)  is a red box pops up with Connection Error and says check if Sublime Text is open and GhostText is installed. I am using the GhostText plugin for Chrome (lastest version) on Windows10. I had the same problem using the FireFox plugin. I cannot find anyone else reporting this issue.

**Comment by Cacodaimon** [comment]
What does the ST console says?

**Comment by dtg581** [comment]
Console just shows some start-up stuff. Nothing appears when I get the red Connection Error pop-up.

Here is the complete console output:

startup, version: 2221 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 2/sublime_text.exe
working dir: /C/WINDOWS/system32
packages path: /C/Users/DTG/AppData/Roaming/Sublime Text 2/Packages
settings path: /C/Users/DTG/AppData/Roaming/Sublime Text 2/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text.exe
Py_GetExecPrefix(): C:\Program Files\Sublime Text 2
Py_GetProgramFullPath(): C:\Program Files\Sublime Text 2\sublime_text.exe
Py_GetPath(): C:\Program Files\Sublime Text 2\python26.zip;C:\Program Files\Sublime Text 2\DLLs;C:\Program Files\Sublime Text 2\lib;C:\Program Files\Sublime Text 2\lib\plat-win;C:\Program Files\Sublime Text 2\lib\lib-tk;C:\Program Files\Sublime Text 2
Py_GetPythonHome(): C:\Program Files\Sublime Text 2
catalogue loaded
found 6 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 1 files for base name Main.sublime-menu
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\CSS\css_completions.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\comment.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\copy_path.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\delete_word.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\detect_indentation.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\duplicate_line.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\echo.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\exec.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\fold.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\font.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\goto_line.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\indentation.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\kill_ring.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\mark.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\new_templates.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\open_file_settings.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\open_in_browser.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\paragraph.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\save_on_focus_lost.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\scroll.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\set_unsaved_view_name.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\side_bar.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\sort.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\swap_line.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\switch_file.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\transform.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\transpose.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Default\trim_trailing_white_space.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Diff\diff.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\HTML\encode_html_entities.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\HTML\html_completions.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Vintage\vintage.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Vintage\vintage_commands.py
Reloading plugin C:\Users\DTG\AppData\Roaming\Sublime Text 2\Packages\Vintage\vintage_motions.py
plugin init time: 0.157566
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.425795
startup cache, total files: 98 cache hits: 98
startup time: 0.507655 (package setup was not run)
loaded 837 snippets
found 1 files for base name Default.sublime-theme
theme loaded
reloading /C/Users/DTG/AppData/Roaming/Sublime Text 2/Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded

**Comment by Cacodaimon** [comment]
GhostText needs Sublime Text 3 .

Once you have ST3 installed I recommend to install package control https://packagecontrol.io/installation and install GhostText via PackageControl and not manually.
