### ISSUE TITLE
[Feature Request] LivePreview Compatibility

### ISSUE THREAD

**Issue by Enteleform** [Cacodaimon/GhostText-for-SublimeText#58]
When using GhostText in a text field which has LivePreview *( SublimeText Forum, StackOverflow, etc. )*, the preview does not update unless you go back & manually edit the original text field:

![ghosttext livepreview issue](https://cloud.githubusercontent.com/assets/10906415/13726807/fc32eb92-e8a5-11e5-90b3-052ef9fa50fe.gif)

It would be great if you could alter the output method so that it affects text fields as if a user was directly manipulating them.

Aside from that, awesome plugin man! :+1:

**Comment by bfred-it** [comment]
The feature already works on StackOverflow by simulating a few:

![live](https://cloud.githubusercontent.com/assets/1402241/13727418/66d07512-e934-11e5-91ff-6f681db456d3.gif)

The issue was being discussed here: https://github.com/Cacodaimon/GhostText-for-Chrome/issues/43

**Comment by Enteleform** [comment]
Gotcha.  Hadn't tested it on StackOverflow & shouldn't have assumed that it would have the same result.

However; the issue demonstration GIF was recorded @ the SublimeText forum, which still behaves in the originally described manner.

**Comment by bfred-it** [comment]
Yes, I wasn't clear. It still is an issue but it's part of the Chrome extension and the feature request is already open then
