### ISSUE TITLE
Syntax support seems broken

### ISSUE THREAD

**Issue by 23maverick23** [Cacodaimon/GhostText-for-SublimeText#59]
First off - great plugin! Very helpful for some workflows I use at the office.

---

**Overview:**

When running GhostText on ST 3103, default syntaxes and host-specific syntaxes aren't working. It looks like you're using the `sublime.find_resources` method [Utils.py#L131-L162](https://github.com/Cacodaimon/GhostText-for-SublimeText/blob/master/GhostTextTools/Utils.py#L131-L162), but doesn't this only search for files within installed packages (and not in standard packages)? Might be best to just have users specify the full syntax path of the `.tmLanuage` file (e.g. `Packages/Markdown/Markdown.tmLanguage`).

If I manually type your syntax lookup code into the ST console, I'm returning an empty array:

```bash
>>> settings = sublime.load_settings('GhostText.sublime-settings')
>>> default_syntax = settings.get('default_syntax', 'Markdown.tmLanguage')
>>> default_syntax
'Markdown.tmLanguage'
>>> resources = sublime.find_resources('*{}'.format(default_syntax))
>>> resources
[]
```

If I just look for `.tmLanugage` resource files, I do get results (so the `sublime.find_resources` method is working), but these are only from installed packages:

```bash
>>> sublime.find_resources('*.tmLanguage')
['Packages/Text/Plain text.tmLanguage', 'Packages/ApacheConf.tmLanguage/ApacheConf.tmLanguage', 'Packages/Emmet/Emmet.tmLanguage', 'Packages/Evernote/Evernote.tmLanguage', 'Packages/FreeMarker/Syntaxes/FreeMarker.tmLanguage', 'Packages/Sass/Syntaxes/Sass.tmLanguage', 'Packages/Swift/Syntaxes/Swift.tmLanguage', 'Packages/Theme - Afterglow/Prefs/Langs/Bower JSON.tmLanguage', 'Packages/Theme - Afterglow/Prefs/Langs/Dockerfile.tmLanguage', 'Packages/Theme - Afterglow/Prefs/Langs/font.tmLanguage', 'Packages/Theme - Afterglow/Prefs/Langs/Git.tmLanguage', 'Packages/Theme - Afterglow/Prefs/Langs/Gruntfile Coffee.tmLanguage', 'Packages/Theme - Afterglow/Prefs/Langs/Gruntfile JS.tmLanguage', 'Packages/Theme - Afterglow/Prefs/Langs/Gulpfile Coffee.tmLanguage', 'Packages/Theme - Afterglow/Prefs/Langs/Gulpfile JS.tmLanguage', 'Packages/Theme - Afterglow/Prefs/Langs/npm JSON.tmLanguage', 'Packages/XML SRP/XML (NSOA).tmlanguage', 'Packages/User/fish.tmLanguage']
```

**Steps to Reproduce:**

1. Set the`default_syntax` settings key to `Markdown.tmLanguage`
2. Open a new textarea connection
3. Syntax file still shows as `Plain Text.tmLanguage`

**Console Output:**

```bash
Start
Listening on: 54346
Bind view with id: 178
Setting on message handler
Default syntax "Markdown.tmLanguage" is not installed!
View with id: 178 closed
Unbind view with id: 178
Stop
```

**Sys Details:**

```bash
>>> sublime.version()
'3103'
>>> sublime.platform()
'osx'
>>> sublime.arch()
'x64'
```

**Comment by bfred-it** [comment]
Thank you for your detailed issue! Hopefully this can be solved by just specifying a file extension and let ST do the matching. I'll give it a try today, but I don't want to get your hopes up because we might already have tried this.

**Comment by 23maverick23** [comment]
I can try submitting a pull request for this. I think the only option is to
require users to store the full path and then match against that.

On Friday, March 25, 2016, Federico Brigante <notifications@github.com>
wrote:

> Thank you for your detailed issue! Hopefully this can be solved by just
> specifying a file extension and let ST do the matching. I'll give it a try
> today, but I don't want to get your hopes up because we might already have
> tried this.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Cacodaimon/GhostText-for-SublimeText/issues/59#issuecomment-201658052>
>


-- 

Ryan Morrissey
e: 23maverick23@gmail.com
m: +1 857.225.1098
w: rymo.io

**Comment by bfred-it** [comment]
Thank you, but this is too complex, the solution I had suggested (*just pass the file extension*) seems to work. I'll send a PR soon so @Cacodaimon can take a look since he knows GT-ST better.

Currently we create a tab and then figure out the syntax. My suggested solution is:

- think of syntaxes in terms of file extension (i.e. `md` instead of `Markdown.tmLanguage`)
- figure out syntax based on host (as already implemented with https://github.com/Cacodaimon/GhostText-for-Chrome/issues/3)
- append file extension to title (open `page title.md` instead of `page title`)

**Comment by bfred-it** [comment]
Let me know what you think @Cacodaimon

**Comment by Cacodaimon** [comment]
@bfred-it 

Sorry I did not noticed the activity in the last days, I was too busy the last year :) , give me some time reading all the issues.

**Comment by bfred-it** [comment]
:tada: :grinning: Welcome back, I realized you were busy so I didn't ping you too much :P

**Comment by Cacodaimon** [comment]
@bfred-it 

It seems to work and it is much lesser code. I like the solution!
